### ISSUE TITLE
選擇 ( 絕對武力 online ) 無法顯示帳號

### ISSUE THREAD

**Issue by fangs0903** [BeanfunLogin/BeanfunLogin#10]
想請問一下是否會修復( 絕對武力 online ) 不顯示帳號的問題， 選擇 ( 絕對武力 online ) 的的時候會顯示沒有帳號...。

我這裡測試後提供一個(一般登入) 可以顯示 (不確定其他登入方式是否可顯示) 的 ( 絕對武力 online ) 帳號的方法 
在 BeanfunClient.Account.cs 新增如圖裡面的那一段
![ScreenShot_20210805043719](https://user-images.githubusercontent.com/43923658/128251726-953e54e1-72a9-4ed6-9f4c-9f65523acd4a.png)
就可以顯示 ( 絕對武力 online ) 的帳號 以及取得OTP。

如有任何錯誤的地方， 請各位前輩不吝指教。

**Comment by xnum** [comment]
看起來是endpoint有新的版本? 能確認其他遊戲也可以正常取得帳號列表嗎?

**Comment by fangs0903** [comment]
其他遊戲也會顯示帳號，可是我只有玩CSO 所以沒有測試其他遊戲是否可以登入，還請大大試一下(沒意外的話應該是可以用的)

順帶一提，如果進入原本的網址(以楓之谷為例)會顯示如圖的介面
![ScreenShot_20210805171935](https://user-images.githubusercontent.com/43923658/128326251-d0919987-f1d7-4f46-8ed1-066162fdc0c6.png)
可是把網址代碼改成CSO的代碼時會顯示如圖的畫面
![ScreenShot_20210805172750](https://user-images.githubusercontent.com/43923658/128327285-2ddd4116-bb99-421b-9299-f56c7dc080ed.png)

在顯示上面兩張圖的時候原本的網址:(https://tw.beanfun.com/beanfun_block/auth.aspx?channel=game_zone&page_and_query=game_start.aspx%3Fservice_code_and_region%3D610074_T9&web_token=webtoken)
會變成下面的網址
(https://tw.beanfun.com/beanfun_block/game_zone/game_server_account_list.aspx?sc=610074&sr=T9&dt=20210805173024)
把這個網址SC 和 SR 改成CSO的代碼 610153 & TN 會顯示像(楓之谷)的介面，這時就可以取得 CSO 的帳號
![ScreenShot_20210805173826](https://user-images.githubusercontent.com/43923658/128330189-a28db719-e052-4282-a0fd-e2aea45f82d3.png)

**Comment by xnum** [comment]
可以試試看 https://github.com/BeanfunLogin/BeanfunLogin/releases/tag/Release-1.11.0.9

**Comment by fangs0903** [comment]
我測試CSO可以正常使用！其餘的請大大測試！
